// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = SECRET_LOGIN;

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onRelayControlChange();

float dht22_humedad;
float dht22_temperatura;
bool relay_Control;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(dht22_humedad, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(dht22_temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(relay_Control, READWRITE, ON_CHANGE, onRelayControlChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
