name: hello_world

environment:
  sdk: ^3.7.0-0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0 
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.15.3
  fl_chart: ^1.0.0





  characters: 1.4.0  
  collection: 1.19.1  
  material_color_utilities: 0.11.1  
  meta: 1.16.0  
  vector_math: 2.1.4  

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.25.15

  _fe_analyzer_shared: ^82.0.0  
  analyzer: ^7.4.5  
  args: ^2.7.0  
  async: ^2.13.0  
  boolean_selector: 2.1.2  
  clock: 1.1.2  
  convert: 3.1.2  
  coverage: ^1.14.0  
  crypto: 3.0.6  
  fake_async: ^1.3.3  
  file: 7.0.1  
  frontend_server_client: 4.0.0  
  glob: ^2.1.3  
  http_multi_server: 3.2.2  
  http_parser: 4.1.2  
  io: 1.0.5  
  js: ^0.6.7  
  leak_tracker: ^10.0.9  
  leak_tracker_flutter_testing: 3.0.9  
  leak_tracker_testing: 3.0.1  
  logging: 1.3.0  
  matcher: 0.12.17  
  mime: 2.0.0  
  node_preamble: 2.0.2  
  package_config: ^2.2.0  
  path: 1.9.1  
  pool: 1.5.1  
  pub_semver: ^2.2.0  
  shelf: 1.4.2  
  shelf_packages_handler: 3.0.2  
  shelf_static: 1.1.3  
  shelf_web_socket: ^3.0.0  
  source_map_stack_trace: 2.1.2  
  source_maps: 0.10.13  
  source_span: 1.10.1  
  stack_trace: 1.12.1  
  stream_channel: 2.1.4  
  string_scanner: 1.4.1  
  sync_http: 0.3.1  
  term_glyph: 1.2.2  
  test_api: 0.7.4  
  test_core: 0.6.8  
  typed_data: 1.4.0  
  vm_service: ^15.0.0  
  watcher: 1.1.1  
  web: ^0.5.1  
  web_socket: ^1.0.1  
  web_socket_channel: ^3.0.3  
  webdriver: ^3.1.0  
  webkit_inspection_protocol: 1.2.1  
  yaml: 3.1.3  

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
  assets:
    - assets/images/cultivo_detalle.jpg
    - assets/images/dashboard_header.jpg
    - assets/images/invernadero-login.jpg
    - assets/fonts/

